# Generated by Django 4.1.2 on 2022-10-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('command', models.CharField(max_length=200)),
                ('envs', models.JSONField()),
            ],
        ),
    ]
